# Generated by Django 4.2.17 on 2025-01-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('admin', 'Admin')], default='cashier', max_length=20),
        ),
    ]
